# Generated by Django 2.0.2 on 2018-03-22 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeContratante', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome do Contratante')),
                ('EmailContratante', models.CharField(blank=True, max_length=80, null=True, verbose_name='Email do Contratante')),
                ('Telefone', models.CharField(blank=True, max_length=80, null=True, verbose_name='Telefone')),
                ('Ramal', models.CharField(blank=True, max_length=80, null=True, verbose_name='Ramal')),
                ('Celular1', models.CharField(blank=True, max_length=80, null=True, verbose_name='Celular 1')),
                ('Celular2', models.CharField(blank=True, max_length=80, null=True, verbose_name='Celular 2')),
                ('Celular3', models.CharField(blank=True, max_length=80, null=True, verbose_name='Celular 3')),
            ],
            options={
                'verbose_name': 'Contratante',
                'verbose_name_plural': 'Contratantes',
            },
        ),
        migrations.CreateModel(
            name='EmpresaContratante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeEmpresa', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome da Empresa')),
                ('EnderecoEmpresa', models.CharField(blank=True, max_length=80, null=True, verbose_name='Endereço da Empresa')),
                ('CidadeEmpresa', models.CharField(blank=True, max_length=80, null=True, verbose_name='Cidade do Evento')),
                ('CEPEmpresa', models.IntegerField(blank=True, null=True, verbose_name='CEP')),
                ('UFEmpresa', models.CharField(blank=True, max_length=3, null=True, verbose_name='UF do Evento')),
                ('EmailEmpresa', models.CharField(blank=True, max_length=80, null=True, verbose_name='Email da Empresa')),
                ('TelefoneEmpresa', models.CharField(blank=True, max_length=80, null=True, verbose_name='Telefone')),
                ('Celular1Empresa', models.CharField(blank=True, max_length=80, null=True, verbose_name='Celular 1')),
                ('Celular2Empresa', models.CharField(blank=True, max_length=80, null=True, verbose_name='Celular 2')),
                ('Celular3Empresa', models.CharField(blank=True, max_length=80, null=True, verbose_name='Celular 3')),
                ('SiteEmpresa', models.CharField(blank=True, max_length=80, null=True, verbose_name='Site')),
            ],
            options={
                'verbose_name': 'EmpresaContratante',
                'verbose_name_plural': 'EmpresaContratantes',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeEvento', models.CharField(blank=True, max_length=80, null=True, verbose_name='Tipo de Evento')),
                ('CidadeEvento', models.CharField(blank=True, max_length=80, null=True, verbose_name='Cidade do Evento')),
                ('CEPEvento', models.IntegerField(blank=True, null=True, verbose_name='CEP')),
                ('UFEvento', models.CharField(blank=True, max_length=3, null=True, verbose_name='UF do Evento')),
                ('DataEventoInicio', models.DateTimeField(blank=True, null=True, verbose_name='Data Inicial do Evento')),
                ('DataEventoFinal', models.DateTimeField(blank=True, null=True, verbose_name='Data Final do Evento')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PublicoEvento', models.IntegerField(blank=True, null=True, verbose_name='Público do Evento')),
                ('ValorMedioBilhete', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Médio do Bilhete')),
                ('DataEventoInicio', models.DateTimeField(blank=True, null=True, verbose_name='Data Inicial do Evento')),
                ('DataEventoFinal', models.DateTimeField(blank=True, null=True, verbose_name='Data Final do Evento')),
                ('Evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legacy.Evento')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
            },
        ),
        migrations.AddField(
            model_name='contratante',
            name='EmpresaContratante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legacy.EmpresaContratante'),
        ),
    ]
