# Generated by Django 2.0.2 on 2018-03-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratante',
            name='Facebook',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='contratante',
            name='Instagram',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='empresacontratante',
            name='Facebook',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='empresacontratante',
            name='Instagram',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Instagram'),
        ),
    ]
