# Generated by Django 2.0.2 on 2018-03-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0002_auto_20180321_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresacontratante',
            name='CidadeEmpresa',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='empresacontratante',
            name='EmailEmpresa',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='empresacontratante',
            name='EnderecoEmpresa',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='empresacontratante',
            name='UFEmpresa',
            field=models.CharField(blank=True, choices=[('MG', 'Minas Gerais'), ('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro'), ('ES', 'Espirito Santo'), ('BA', 'Bahia')], max_length=3, null=True, verbose_name='UF'),
        ),
    ]
