# Generated by Django 2.0.2 on 2018-03-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0004_auto_20180322_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratante',
            name='Aniversario',
            field=models.DateField(blank=True, null=True, verbose_name='Aniversário'),
        ),
    ]
