# Generated by Django 2.0.2 on 2018-03-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0005_contratante_aniversario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome do Musico')),
                ('Instrumento', models.CharField(blank=True, choices=[('ACORDEON', 'Acordeon'), ('BACK', 'Backing Vocal'), ('BATERIA', 'Bateria'), ('DJ', 'DJ'), ('GUITARRA', 'Guitarra'), ('VIOLAO/GUITARRA', 'Violão e Guitarra'), ('TECLADO', 'Teclado'), ('TROMPETE', 'Trompete'), ('TROMBONE', 'Trombone'), ('PERCUSSAO', 'Percussão'), ('SAX', 'Sax'), ('VIOLA', 'Viola'), ('VIOLAO', 'Violão')], max_length=30, null=True, verbose_name='Estado')),
                ('Especialidade', models.CharField(blank=True, choices=[('ESTU', 'Estudio'), ('SHOW', 'Show'), ('ESSH', 'Show e Estudio')], max_length=4, null=True, verbose_name='Especialidade')),
                ('TipoContratacao', models.CharField(blank=True, choices=[('FREE', 'Free Lancer'), ('FIXO', 'Fixo Assalariado')], max_length=4, null=True, verbose_name='Tipo de Contrataçao')),
                ('ValorCache', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor')),
                ('Email', models.CharField(blank=True, max_length=80, null=True, verbose_name='Email do Musico')),
                ('Telefone', models.CharField(blank=True, max_length=80, null=True, verbose_name='Telefone')),
                ('Celular1', models.CharField(blank=True, max_length=80, null=True, verbose_name='Celular 1')),
                ('Celular2', models.CharField(blank=True, max_length=80, null=True, verbose_name='Celular 2')),
                ('Instagram', models.CharField(blank=True, max_length=80, null=True, verbose_name='Instagram')),
                ('Facebook', models.CharField(blank=True, max_length=80, null=True, verbose_name='Facebook')),
                ('Endereco', models.CharField(blank=True, max_length=80, null=True, verbose_name='Endereço')),
                ('Cidade', models.CharField(blank=True, max_length=80, null=True, verbose_name='Cidade')),
                ('UF', models.CharField(blank=True, choices=[('MG', 'Minas Gerais'), ('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro'), ('ES', 'Espirito Santo'), ('BA', 'Bahia')], max_length=3, null=True, verbose_name='Estado')),
                ('CEP', models.IntegerField(blank=True, null=True, verbose_name='CEP')),
                ('Aniversario', models.DateField(blank=True, null=True, verbose_name='Aniversário')),
            ],
            options={
                'verbose_name': 'Musico',
                'verbose_name_plural': 'Musicos',
            },
        ),
    ]
