# Generated by Django 2.0.2 on 2018-03-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0006_musico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musico',
            name='Instrumento',
            field=models.CharField(blank=True, choices=[('ACORDEON', 'Acordeon'), ('BACK', 'Backing Vocal'), ('BAIXO', 'Baixo'), ('BATERIA', 'Bateria'), ('DJ', 'DJ'), ('GUITARRA', 'Guitarra'), ('VIOLAO/GUITARRA', 'Violão e Guitarra'), ('TECLADO', 'Teclado'), ('TROMPETE', 'Trompete'), ('TROMBONE', 'Trombone'), ('PERCUSSAO', 'Percussão'), ('SAX', 'Sax'), ('VIOLA', 'Viola'), ('VIOLAO', 'Violão')], max_length=30, null=True, verbose_name='Instrumento'),
        ),
    ]
