# Generated by Django 2.0.2 on 2018-03-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0008_musico_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome do Produtor')),
                ('DescricaoServico', models.CharField(blank=True, choices=[('EXECUTIVO', 'Produtor Executivo'), ('GERAL', 'Produtor Geral'), ('PALCO', 'Produtor de Palco'), ('TECNICO', 'Produtor Tecnico'), ('MUSICAL', 'Produtor Musical'), ('ARTISTICO', 'Artistico')], max_length=30, null=True, verbose_name='Descriçao do Serviço')),
                ('Score', models.IntegerField(blank=True, choices=[(1, '1 Estrela (Muito Ruim)'), (2, '2 Estrelas (Ruim)'), (3, '3 Estrelas (Medio)'), (4, '4 Estrelas (Bom)'), (5, '5 Estrelas (Muito Bom)')], max_length=3, null=True, verbose_name='Score')),
                ('TipoContratacao', models.CharField(blank=True, choices=[('FREE', 'Free Lancer'), ('FIXO', 'Fixo Assalariado')], max_length=4, null=True, verbose_name='Tipo de Contrataçao')),
                ('ValorCache', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor')),
                ('Email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email do Musico')),
                ('Telefone', models.CharField(blank=True, max_length=80, null=True, verbose_name='Telefone')),
                ('Celular1', models.CharField(blank=True, max_length=80, null=True, verbose_name='Celular 1')),
                ('Celular2', models.CharField(blank=True, max_length=80, null=True, verbose_name='Celular 2')),
                ('Instagram', models.CharField(blank=True, max_length=80, null=True, verbose_name='Instagram')),
                ('Facebook', models.CharField(blank=True, max_length=80, null=True, verbose_name='Facebook')),
                ('Endereco', models.CharField(blank=True, max_length=80, null=True, verbose_name='Endereço')),
                ('Cidade', models.CharField(blank=True, max_length=80, null=True, verbose_name='Cidade')),
                ('UF', models.CharField(blank=True, choices=[('MG', 'Minas Gerais'), ('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro'), ('ES', 'Espirito Santo'), ('BA', 'Bahia')], max_length=3, null=True, verbose_name='Estado')),
                ('CEP', models.IntegerField(blank=True, null=True, verbose_name='CEP')),
                ('Aniversario', models.DateField(blank=True, null=True, verbose_name='Nascimento')),
            ],
            options={
                'verbose_name': 'Produtor',
                'verbose_name_plural': 'Produtores',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome do Tecnico')),
                ('DescricaoServico', models.CharField(blank=True, choices=[('ROADIE', 'Roadie'), ('CARREGADOR', 'Carregador'), ('MOTORISTA', 'Motorista'), ('SEGURANCA', 'Segurança'), ('MAQUEADOR', 'Maqueador'), ('CABELEIREIRO', 'Cabeleireiro')], max_length=30, null=True, verbose_name='Descriçao do Serviço')),
                ('Score', models.IntegerField(blank=True, choices=[(1, '1 Estrela (Muito Ruim)'), (2, '2 Estrelas (Ruim)'), (3, '3 Estrelas (Medio)'), (4, '4 Estrelas (Bom)'), (5, '5 Estrelas (Muito Bom)')], max_length=3, null=True, verbose_name='Score')),
                ('TipoContratacao', models.CharField(blank=True, choices=[('FREE', 'Free Lancer'), ('FIXO', 'Fixo Assalariado')], max_length=4, null=True, verbose_name='Tipo de Contrataçao')),
                ('ValorCache', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor')),
                ('Email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email do Musico')),
                ('Telefone', models.CharField(blank=True, max_length=80, null=True, verbose_name='Telefone')),
                ('Celular1', models.CharField(blank=True, max_length=80, null=True, verbose_name='Celular 1')),
                ('Celular2', models.CharField(blank=True, max_length=80, null=True, verbose_name='Celular 2')),
                ('Instagram', models.CharField(blank=True, max_length=80, null=True, verbose_name='Instagram')),
                ('Facebook', models.CharField(blank=True, max_length=80, null=True, verbose_name='Facebook')),
                ('Endereco', models.CharField(blank=True, max_length=80, null=True, verbose_name='Endereço')),
                ('Cidade', models.CharField(blank=True, max_length=80, null=True, verbose_name='Cidade')),
                ('UF', models.CharField(blank=True, choices=[('MG', 'Minas Gerais'), ('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro'), ('ES', 'Espirito Santo'), ('BA', 'Bahia')], max_length=3, null=True, verbose_name='Estado')),
                ('CEP', models.IntegerField(blank=True, null=True, verbose_name='CEP')),
                ('Aniversario', models.DateField(blank=True, null=True, verbose_name='Nascimento')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staffs',
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome do Tecnico')),
                ('DescricaoServico', models.CharField(blank=True, choices=[('SOM', 'Tecnico de Som Palco e PA'), ('SOMP', 'Tecnico de Som PA'), ('SOMPL', 'Tecnico de Som Palco'), ('LUZ', 'Tecnico de Luz'), ('LED', 'Tecnico de LED - VJ')], max_length=30, null=True, verbose_name='Descriçao do Serviço')),
                ('Score', models.IntegerField(blank=True, choices=[(1, '1 Estrela (Muito Ruim)'), (2, '2 Estrelas (Ruim)'), (3, '3 Estrelas (Medio)'), (4, '4 Estrelas (Bom)'), (5, '5 Estrelas (Muito Bom)')], max_length=3, null=True, verbose_name='Score')),
                ('TipoContratacao', models.CharField(blank=True, choices=[('FREE', 'Free Lancer'), ('FIXO', 'Fixo Assalariado')], max_length=4, null=True, verbose_name='Tipo de Contrataçao')),
                ('ValorCache', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor')),
                ('Email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email do Musico')),
                ('Telefone', models.CharField(blank=True, max_length=80, null=True, verbose_name='Telefone')),
                ('Celular1', models.CharField(blank=True, max_length=80, null=True, verbose_name='Celular 1')),
                ('Celular2', models.CharField(blank=True, max_length=80, null=True, verbose_name='Celular 2')),
                ('Instagram', models.CharField(blank=True, max_length=80, null=True, verbose_name='Instagram')),
                ('Facebook', models.CharField(blank=True, max_length=80, null=True, verbose_name='Facebook')),
                ('Endereco', models.CharField(blank=True, max_length=80, null=True, verbose_name='Endereço')),
                ('Cidade', models.CharField(blank=True, max_length=80, null=True, verbose_name='Cidade')),
                ('UF', models.CharField(blank=True, choices=[('MG', 'Minas Gerais'), ('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro'), ('ES', 'Espirito Santo'), ('BA', 'Bahia')], max_length=3, null=True, verbose_name='Estado')),
                ('CEP', models.IntegerField(blank=True, null=True, verbose_name='CEP')),
                ('Aniversario', models.DateField(blank=True, null=True, verbose_name='Nascimento')),
            ],
            options={
                'verbose_name': 'Tecnico',
                'verbose_name_plural': 'Tecnicos',
            },
        ),
        migrations.AddField(
            model_name='contratante',
            name='Score',
            field=models.IntegerField(blank=True, choices=[(1, '1 Estrela (Muito Ruim)'), (2, '2 Estrelas (Ruim)'), (3, '3 Estrelas (Medio)'), (4, '4 Estrelas (Bom)'), (5, '5 Estrelas (Muito Bom)')], max_length=3, null=True, verbose_name='Score'),
        ),
        migrations.AddField(
            model_name='empresacontratante',
            name='Score',
            field=models.IntegerField(blank=True, choices=[(1, '1 Estrela (Muito Ruim)'), (2, '2 Estrelas (Ruim)'), (3, '3 Estrelas (Medio)'), (4, '4 Estrelas (Bom)'), (5, '5 Estrelas (Muito Bom)')], max_length=3, null=True, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='musico',
            name='Score',
            field=models.IntegerField(blank=True, choices=[(1, '1 Estrela (Muito Ruim)'), (2, '2 Estrelas (Ruim)'), (3, '3 Estrelas (Medio)'), (4, '4 Estrelas (Bom)'), (5, '5 Estrelas (Muito Bom)')], max_length=3, null=True, verbose_name='Score'),
        ),
    ]
